# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ef3eff4a036e7b70a357508d96c091acb9376cf33ded28d0c49ee686684ae7b61163cdba9e8df095e4e44ac2f373806044aa18597e638564a25c0361f99984f

test:
  secret_key_base: fc09dcc44e91fc373ed333e9a39fa51a24e8659801f8782e3517eb6968c1adb24555515029fccb9c8f587037889697914ce7ef2fc034f0886fc81b9dfd50fc5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
